### PR TITLE
Feat: pass MongoClientSettings into GoContext constructor to create an instance of MongoClient

### PR DESCRIPTION
**Pull request by 0xc0dec0ffee**
As title,
Thanks :)
Jeff

### CODE REVIEW

**Comment by 0xc0dec0ffee** [comment]
@yamiew00 🙏

**Comment by yamiew00** [comment]
@0xc0dec0ffee 
Ok, i'll publish a new version containing the support of MongoClientSettings ASAP

**Comment by yamiew00** [comment]
@0xc0dec0ffee
[6.0.0 released](https://github.com/yamiew00/MongoGogo/releases/tag/6.0.0)

**Comment by 0xc0dec0ffee** [comment]
@yamiew00 Thank you so much ~~~

**Pull request closed without merging**
